CATALOG = [
    {
        "name": "Rice",
        "category": "Grains",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["chawal", "basmati"],
    },
    {
        "name": "Wheat flour",
        "category": "Grains",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 90,
        "location": "Pantry",
        "aliases": ["atta"],
    },
    {
        "name": "Toor dal",
        "category": "Pulses",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["arhar", "pigeon peas"],
    },
    {
        "name": "Moong dal",
        "category": "Pulses",
        "unit": "kg",
        "pack_size": 0.5,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["mung"],
    },
    {
        "name": "Chickpeas",
        "category": "Pulses",
        "unit": "kg",
        "pack_size": 0.5,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["chana"],
    },
    {
        "name": "Milk",
        "category": "Dairy",
        "unit": "L",
        "pack_size": 0.5,
        "shelf_days": 3,
        "location": "Fridge",
        "aliases": ["doodh"],
    },
    {
        "name": "Curd",
        "category": "Dairy",
        "unit": "kg",
        "pack_size": 0.4,
        "shelf_days": 5,
        "location": "Fridge",
        "aliases": ["dahi", "yogurt"],
    },
    {
        "name": "Paneer",
        "category": "Dairy",
        "unit": "kg",
        "pack_size": 0.2,
        "shelf_days": 3,
        "location": "Fridge",
        "aliases": [],
    },
    {
        "name": "Butter",
        "category": "Dairy",
        "unit": "kg",
        "pack_size": 0.1,
        "shelf_days": 30,
        "location": "Fridge",
        "aliases": [],
    },
    {
        "name": "Tomatoes",
        "category": "Vegetables",
        "unit": "kg",
        "pack_size": 0.5,
        "shelf_days": 5,
        "location": "Fridge",
        "aliases": ["tamatar"],
    },
    {
        "name": "Onions",
        "category": "Vegetables",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 20,
        "location": "Pantry",
        "aliases": ["pyaaz"],
    },
    {
        "name": "Potatoes",
        "category": "Vegetables",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 20,
        "location": "Pantry",
        "aliases": ["aloo"],
    },
    {
        "name": "Spinach",
        "category": "Vegetables",
        "unit": "kg",
        "pack_size": 0.25,
        "shelf_days": 3,
        "location": "Fridge",
        "aliases": ["palak"],
    },
    {
        "name": "Carrots",
        "category": "Vegetables",
        "unit": "kg",
        "pack_size": 0.5,
        "shelf_days": 7,
        "location": "Fridge",
        "aliases": ["gajar"],
    },
    {
        "name": "Capsicum",
        "category": "Vegetables",
        "unit": "kg",
        "pack_size": 0.25,
        "shelf_days": 5,
        "location": "Fridge",
        "aliases": ["bell pepper"],
    },
    {
        "name": "Apples",
        "category": "Fruit",
        "unit": "pcs",
        "pack_size": 4,
        "shelf_days": 14,
        "location": "Fridge",
        "aliases": [],
    },
    {
        "name": "Bananas",
        "category": "Fruit",
        "unit": "pcs",
        "pack_size": 6,
        "shelf_days": 4,
        "location": "Counter",
        "aliases": ["kela"],
    },
    {
        "name": "Cooking oil",
        "category": "Essentials",
        "unit": "L",
        "pack_size": 1,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": [],
    },
    {
        "name": "Sugar",
        "category": "Essentials",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 365,
        "location": "Pantry",
        "aliases": [],
    },
    {
        "name": "Salt",
        "category": "Essentials",
        "unit": "kg",
        "pack_size": 1,
        "shelf_days": 365,
        "location": "Pantry",
        "aliases": [],
    },
    {
        "name": "Tea",
        "category": "Beverages",
        "unit": "g",
        "pack_size": 250,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["chai"],
    },
    {
        "name": "Coffee",
        "category": "Beverages",
        "unit": "g",
        "pack_size": 100,
        "shelf_days": 90,
        "location": "Pantry",
        "aliases": [],
    },
    {
        "name": "Bread",
        "category": "Bakery",
        "unit": "pcs",
        "pack_size": 1,
        "shelf_days": 3,
        "location": "Pantry",
        "aliases": [],
    },
    {
        "name": "Oats",
        "category": "Grains",
        "unit": "kg",
        "pack_size": 0.5,
        "shelf_days": 90,
        "location": "Pantry",
        "aliases": [],
    },
    {
        "name": "Almonds",
        "category": "Nuts",
        "unit": "g",
        "pack_size": 250,
        "shelf_days": 90,
        "location": "Pantry",
        "aliases": ["badam"],
    },
    {
        "name": "Turmeric",
        "category": "Spices",
        "unit": "g",
        "pack_size": 100,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["haldi"],
    },
    {
        "name": "Cumin",
        "category": "Spices",
        "unit": "g",
        "pack_size": 100,
        "shelf_days": 180,
        "location": "Pantry",
        "aliases": ["jeera"],
    },
    {
        "name": "Frozen peas",
        "category": "Frozen",
        "unit": "kg",
        "pack_size": 0.5,
        "shelf_days": 90,
        "location": "Freezer",
        "aliases": [],
    },
]
# Shelf-days are editable planning intervals, not expiry dates or safety advice.
